//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animalia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
